//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lastone.models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedStudentsId
    {
        public int Id { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
